name: Deploy to S3
on:
  push:
    tags:
      - v*
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      S3_URL: ${{ secrets.PROD_S3_URL }}
      REACT_APP_API_DOMAIN: ${{ secrets.PROD_API_URL }}
      REACT_APP_MAPLIBRE_MAP_STYLE: ${{ secrets.MAP_STYLE }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: yarn
      - run: yarn run build
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - run: yarn s3p sync -y -t $S3_URL
